# config borrowed from https://github.com/lovell/sharp/blob/master/.travis.yml
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
osx_image: xcode7.3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/vips; fi
